version: "3.3"
services:
    mysql:
        image: "mysql:latest"
        environment:
            POSTGRES_USER: "mysql"
            POSTGRES_PASSWORD: "mysql"
            POSTGRES_DB: "hyvor-blogs"
        # volumes: 
        #     - pgsql:/var/lib/postgresql/data

    meilisearch:
        image: "meilisearch/meilisearch:latest"
        depends_on:
            - mysql
            
    app:
        image: "hyvor/hyvor-blogs:latest"
        ports:
            - "127.0.0.1:5000:5000"
        env_file:
            - .env
        depends_on:
            - meilisearch
        command: "sh -c 'php /var/www/app/backend/artisan migrate --force && /usr/bin/supervisord'"

# volumes:
#     pgsql: