services:
  hyvor-blogs-build:
    container_name: hyvor-blogs-build
    build:
      context: ../../
      target: final
    env_file:
      - .env.build
    labels:
      traefik.enable: true
      traefik.http.routers.hyvor-blogs-build.rule: Host(`blogs.build.hyvor.localhost`)
      traefik.http.routers.hyvor-blogs-build.entrypoints: https
      traefik.http.routers.hyvor-blogs-build.tls: true

      traefik.http.routers.hyvor-blogs-subdir.rule: HostRegexp(`^.+\.b\.build\.hyvor\.localhost$`)
      traefik.http.routers.hyvor-blogs-subdir.entrypoints: http

      traefik.http.services.hyvor-blogs-build.loadbalancer.server.port: 8080
    command: >
      sh -c "/app/symfony/bin/console doctrine:migrations:migrate --no-interaction && /app/run"
    networks:
      hyvor-network:
        aliases:
          - blogs.build.hyvor.internal
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: hyvor-blogs-build-postgres
    image: postgres:16.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyvor_blogs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hyvor-network

networks:
  hyvor-network:
    external: true
