version: '3.3'
services:
  mysql:
    # mysql 8.0
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: hyvor_blogs
    ports:
      - "3306:3306"
    expose:
      -   3306
    volumes:
      - ~/mysql:/var/lib/mysql:delegated
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  meilisearch:
    image: getmeili/meilisearch:v1.0
    restart: unless-stopped
    ports:
      - '7700:7700'

volumes:
  mysql:
  redis: