version: "3.9"

services:
  hyvor-blogs:
    image: hyvor/blogs:${IMAGE_VERSION:-latest}
    env_file: .env
    labels:
      - "traefik.enable=true"

      # blogs.hyvor.com and hyvorblogs.io (Cloudflare SSL)
      - "traefik.http.routers.hyvorblogs.entrypoints=web"
      - "traefik.http.routers.hyvorblogs.rule=PathPrefix(`/`)"
      - "traefik.http.routers.hyvorblogs.service=hyvorblogs-service"
      - "traefik.http.services.hyvorblogs-service.loadbalancer.server.port=80"

      # custom domain (with SSL support)
      - "traefik.tcp.routers.custom-domain.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.custom-domain.entrypoints=websecure"
      - "traefik.tcp.routers.custom-domain.tls=true"
      - "traefik.tcp.routers.custom-domain.tls.passthrough=true"
      - "traefik.tcp.routers.custom-domain.service=custom-domain-service"
      - "traefik.tcp.services.custom-domain-service.loadbalancer.server.port=443"

      # caddy metrics
      - "traefik.http.routers.caddymetrics.entrypoints=caddymetrics"
      - "traefik.http.routers.caddymetrics.rule=PathPrefix(`/`)"
      - "traefik.http.routers.caddymetrics.service=caddymetrics-service"
      - "traefik.http.services.caddymetrics-service.loadbalancer.server.port=9666"

      # app metrics
      - "traefik.http.routers.appmetrics.entrypoints=appmetrics"
      - "traefik.http.routers.appmetrics.rule=PathPrefix(`/`)"
      - "traefik.http.routers.appmetrics.service=appmetrics-service"
      - "traefik.http.services.appmetrics-service.loadbalancer.server.port=9667"
    healthcheck:
      test: 'curl -f --header "Host: $DOMAIN_APP" http://localhost || exit 1 && curl -f --header "Host: $DOMAIN_APP" http://localhost/api/special/health || exit 1'

    volumes:
      # caddy data
      - caddy_data:/data/caddy

  traefik:
    image: traefik:v3.6.4
    container_name: traefik
    command:
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.caddymetrics.address=:9666"
      - "--entrypoints.appmetrics.address=:9667"
      - "--log=true"
      - "--log.level=ERROR"
      - "--log.filePath=/var/log/traefik.log"
    ports:
      - "80:80"
      - "443:443"
      - "${METRICS_IP:-127.0.0.1}:9666:9666" # Caddy Metrics
      - "${METRICS_IP:-127.0.0.1}:9667:9667" # App Metrics
      # - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/log:/var/log"

volumes:
  caddy_data:
