version: "3.3"
services:
  hb-pgsql:
    image: "postgres:16.6"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyvor_blogs
    expose:
      - 5432
    volumes:
      - hb-pgsql-data:/var/lib/postgresql/data

  hb-app:
    image: "hyvor/blogs:${IMAGE_VERSION:-latest}"
    ports:
      - "127.0.0.1:5000:80"
    env_file:
      - .env.hb
    depends_on:
      - hb-pgsql

volumes:
  hb-pgsql-data:
