version: "3.3"
services:
    hb-mysql:
        image: "mysql:latest"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ROOT_HOST: "%"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: hyvor_blogs
        expose:
            - 3306
        volumes:
            - hb-mysql-data:/var/lib/mysql

    hb-pgsql:
        image: "postgres:16.6"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hyvor_blogs
        expose:
            - 5432
        volumes:
            - hb-pgsql-data:/var/lib/postgresql/data

    hb-app:
        image: "hyvor/blogs:latest"
        ports:
            - "127.0.0.1:5000:80"
        env_file:
            - .env.hb
        depends_on:
            - hb-mysql

volumes:
    hb-mysql-data:
