version: "3.9"

services:
    hyvor-blogs:
        image: hyvor/blogs:${IMAGE_VERSION:-latest}
        env_file: .env
        labels:
            - "traefik.enable=true"
            
            # custom domain (with SSL support)
            - "traefik.tcp.routers.custom-domain.rule=HostSNI(`*`)"
            - "traefik.tcp.routers.custom-domain.entrypoints=websecure"
            - "traefik.tcp.routers.custom-domain.tls=true"
            - "traefik.tcp.routers.custom-domain.tls.passthrough=true"
            - "traefik.tcp.services.custom-service.loadbalancer.server.port=443"

            # blogs.hyvor.com and hyvorblogs.io (Cloudflare SSL)
            - "traefik.http.routers.hyvorblogs.entrypoints=web"
            - "traefik.http.routers.hyvorblogs.rule=PathPrefix(`/`)"
            - "traefik.http.services.hyvorblogs.loadbalancer.server.port=80"
        healthcheck:
            test: 'curl -f http://localhost || exit 1 && curl -f http://localhost/api/special/health || exit 1'

    traefik:
        image: traefik:v2.9
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--log=true"
            - "--log.level=DEBUG"
            - "--log.filePath=/var/log/traefik.log"
            - "--accesslog=true"
            - "--accesslog.filePath=/var/log/access.log"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080" # Uncomment to enable Traefik dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./traefik:/etc/traefik"
            - "./traefik/log:/var/log"