<?php

namespace Tests\Feature\ConsoleAPI\ApiUser;

use App\Data\Enums\BlogTypeEnum;
use App\Models\Blog;
use App\Models\BlogVariant;
use App\Models\Theme;
use App\Models\ThemeVersion;
use Database\Factories\BlogFactory;
use Hyvor\Internal\Resource\ResourceFake;
use Illuminate\Database\Eloquent\Factories\Sequence;
use Tests\Case\DatabaseTestCase;

class CreateBlogTest extends DatabaseTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // themes are needed to create a blog
        Theme::factory()
            ->count(2)
            ->state(
                new Sequence(
                    ['name' => 'hello'],
                    ['name' => 'blank']
                )
            )
            ->has(ThemeVersion::factory(), 'versions')
            ->create();
    }

    public function testValidates(): void
    {
        $this->consoleUserApi('POST', '/blog')
            ->assertUnprocessable()
            ->assertSee(['name', 'required']);

        $this->consoleUserApi('POST', '/blog', ['name' => 'test'])
            ->assertUnprocessable()
            ->assertSee(['subdomain', 'required']);


        $this->consoleUserApi('POST', '/blog', [
            'name' => 'test',
            'subdomain' => 'new'
        ])
            ->assertUnprocessable()
            ->assertSee('Subdomain is reserved');
    }

    public function testCreatesBlog(): void
    {
        ResourceFake::enable();

        $blogId = $this->consoleUserApi('POST', '/blog', [
            'name' => 'Testing',
            'subdomain' => 'new-blog',
        ])
            ->assertOk()
            ->assertJsonPath('subdomain', 'new-blog')
            ->assertJsonPath('type', 'default')
            ->assertJsonPath('role', 'owner')
            ->json()['id'];

        $blog = Blog::findOrFail($blogId);
        $this->assertInstanceOf(Blog::class, $blog);
        $this->assertEquals('new-blog', $blog->subdomain);
        $this->assertEquals('127.0.0.1', $blog->ip);
        $this->assertEquals(BlogTypeEnum::DEFAULT, $blog->type);
        $this->assertEquals(1, BlogVariant::where('blog_id', $blogId)->count());

        ResourceFake::assertRegistered(1, $blogId);
    }

    public function testCreatesDevBlog(): void
    {
        ResourceFake::enable();

        $blogId = $this->consoleUserApi('POST', '/blog', [
            'name' => 'Testing',
            'is_dev' => true,
        ])
            ->assertOk()
            ->assertJsonPath('role', 'owner')
            ->json()['id'];

        $blog = Blog::find($blogId);
        $this->assertInstanceOf(Blog::class, $blog);
        $this->assertEquals(BlogTypeEnum::DEV, $blog->type);
        $this->assertMatchesRegularExpression(
            '/^dev-[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i',
            $blog->subdomain
        );

        ResourceFake::assertRegistered(1, $blogId);
    }

    public function testCannotCreateABlogWithAlreadyExistingSubdomain(): void
    {
        $blog = BlogFactory::withAccess();

        $this->consoleUserApi('POST', '/blog', [
            'name' => 'Testing',
            'subdomain' => $blog->subdomain,
        ])
            ->assertUnprocessable()
            ->assertSee(['Subdomain', 'taken']);
    }

    public function testCannotCreateIfTheUserHas2BlogsWithoutSubscription(): void
    {
        BlogFactory::withAccess();
        BlogFactory::withAccess();

        $this->consoleUserApi('POST', '/blog', [
            'name' => 'Testing',
            'subdomain' => 'some-subdomain'
        ])
            ->assertUnprocessable()
            ->assertSee('Please upgrade at least one of your blogs to create more');
    }

    public function testAllowsWhenYouHaveASubscription(): void
    {
        $this->markTestSkipped();
        // TODO: Subscription check
        $blog1 = BlogFactory::withAccess();
        $this->createSubscription($blog1);
        BlogFactory::withAccess();

        $this->consoleUserApi('POST', '/blog', [
            'name' => 'Testing',
            'subdomain' => 'some-subdomain'
        ])
            ->assertOk();
    }

}
