[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:php-fpm]
command=php-fpm8.3 -F
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=0

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile
stdout_logfile=/var/log/caddy.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/caddy.log
stderr_logfile_maxbytes=0
autorestart=true
startretries=0

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/app/backend/artisan queue:work --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=~/worker.log
stopwaitsecs=3600

[program:scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while [ true ]; do (php /var/www/app/backend/artisan schedule:run --verbose --no-interaction &); sleep 60; done"
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=~/scheduler.log
stopwaitsecs=60

# run only once
[program:cache]
command=/bin/bash -c "cd /var/www/app/backend && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan event:cache"
autostart=true
autorestart=false