[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

# https://askubuntu.com/a/932612
[supervisorctl]

[program:frankenphp]
command=frankenphp run --config /etc/caddy/Caddyfile
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
autorestart=true
startretries=0
user=chef

# [program:messenger-scheduler]
# command=php /app/backend/bin/console messenger:consume scheduler_default --time-limit=3600 --memory-limit=128M --limit=100
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr
# stdout_logfile_maxbytes=0
# stderr_logfile_maxbytes=0
# user=chef

# [program:messenger-async]
# command=php /app/backend/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M --limit=100
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr
# stdout_logfile_maxbytes=0
# stderr_logfile_maxbytes=0
# user=chef
