#!/usr/bin/env sh

set -e

cleanup() {
    echo "Cleaning up..."
    jobs -p | xargs -r kill
    exit 0
}

(
    trap cleanup INT TERM;

    # Check if --no-caddy is passed as an argument
    no_caddy=false
    for arg in "$@"; do
        if [ "$arg" = "--no-caddy" ]; then
            no_caddy=true
        break
        fi
    done

    npm run dev --prefix ./frontend &
    composer serve --working-dir=./backend &

    if [ "$no_caddy" = false ]; then
        caddy run --config ./meta/dev/Caddyfile.dev &
    fi

    wait
)