#!/usr/bin/env sh

set -e

cleanup() {
    echo "Cleaning up..."
    jobs -p | xargs -r kill
    exit 0
}

(
  trap cleanup SIGINT SIGTERM;
  
  npm run dev --prefix ./frontend &
  composer serve --working-dir=./backend &
  caddy run --config ./meta/dev/Caddyfile.dev &
  
  wait
)