version: "3.9"

services:
    hyvor-blogs:
        image: hyvor/blogs:${IMAGE_VERSION:-latest}
        env_file: .env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.<service>.entrypoints=web"
            - "traefik.http.routers.<service>.rule=PathPrefix(`/`)"
        healthcheck:
            test: 'curl -f http://localhost || exit 1 && curl -f http://localhost/api/special/health || exit 1'

    traefik:
        image: traefik:v2.9
        container_name: traefik
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            # - "8080:8080" # Uncomment to enable Traefik dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"