name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - self-hosting

jobs:
  frontend-check:
    name: "Svelte / TS Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t frontend-dev . --target frontend-dev

      - name: Run Svelte Check
        run: docker run frontend-dev npm run check

  prettier:
    name: "Svelte / Prettier"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t frontend-ci . --target frontend-dev

      - name: Run prettier
        run: docker run frontend-ci npm run lint

  symfony-phpstan:
    name: "Symfony / PHPStan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t backend-dev . --target backend-dev

      - name: Run PHPStan
        run: |
          docker run \
          -w /app/symfony \
          backend-dev ./vendor/bin/phpstan analyse --memory-limit=1G --ansi

  symfony-php-tests:
    name: "Symfony / PHP Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up services
        run: |
          docker network create ci
          docker compose -f meta/ci/compose.ci.yaml up -d

      - name: Build Docker image
        run: docker build -t backend-dev . --target backend-dev

      - name: Run Tests
        run: |
          touch coverage.xml
          docker run \
          -w /app/symfony \
          -e DATABASE_URL="postgresql://postgres:postgres@postgres:5432/hyvor_blogs_testing?serverVersion=16&charset=utf8" \
          --network ci \
          --mount type=bind,source=$(pwd)/coverage.xml,target=/app/symfony/coverage.xml \
          backend-dev sh -c "
          php -d memory_limit=1024M bin/console doctrine:migrations:migrate --env=test --no-interaction &&
          php -d memory_limit=1024M ./vendor/bin/phpunit --coverage-clover /app/symfony/coverage.xml"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.HYVOR_ORG_CODECOV_TOKEN }}
          slug: hyvor/core
          files: /app/symfony/coverage.xml
