name: Test

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            coverage: "none"
            php-version: "8.1"
            ini-file: development
            tools: composer:v2
            extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, intl

      -   name: Install dependencies
          env:
            REPMAN_TOKEN: ${{ secrets.REPMAN_TOKEN }}
          run: |
            npm install --omit=dev
            composer config --global --auth http-basic.hyvor.repo.repman.io token ${REPMAN_TOKEN}
            composer update --ansi --no-progress --ignore-platform-req=ext-mysql

      -   name: Run tests
          run: composer test